[project]
authors = [
  {name = "Your Name", email = "you@example.com"},
]
dependencies = [
  "boto3 (>=1.36.25,<2.0.0)",
  "langchain (>=0.3.19,<0.4.0)",
  "aws-cdk-lib (>=2.180.0,<3.0.0)",
]
description = ""
name = "bedrock-sample"
readme = "README.md"
requires-python = ">=3.13,<4.0"
version = "0.1.0"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
boto3-stubs = {version = "^1.36.26", extras = ["bedrock", "bedrock-runtime", "bedrock-agent-runtime", "boto3"]}
constructs = "^10.4.2"
mypy = "^1.15.0"
pytest = "^8.3.4"

[tool.pytest.ini_options]
addopts = "-ra -q -s"
testpaths = [
  "tests",
]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=2.0.0,<3.0.0"]
